export const USER_STATES = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
];

export const GENDERS = ['Male', 'Female', 'Other'];

export const DEGREES = [
  'High School',
  'Bachelor',
  'Master',
  'PhD',
  'Diploma',
  'Certification',
];

export const DOMAINS = [
  'Software Development',
  'Data Science',
  'UI/UX Design',
  'DevOps',
  'Quality Assurance',
  'Project Management',
];

export const SUB_DOMAINS = {
  'Software Development': ['Frontend', 'Backend', 'Full Stack', 'Mobile'],
  'Data Science': ['ML Engineering', 'Data Analysis', 'Analytics', 'AI'],
  'UI/UX Design': ['UI Design', 'UX Research', 'Product Design', 'Web Design'],
  'DevOps': ['Cloud Engineering', 'Infrastructure', 'CI/CD', 'Kubernetes'],
  'Quality Assurance': ['Manual Testing', 'Automation', 'Performance Testing'],
  'Project Management': ['Agile', 'Scrum', 'Kanban', 'Waterfall'],
};