export const DUMMY_USERS = [
  {
    id: '1',
    firstName: 'Dave',
    lastName: 'Richards',
    email: 'dave.richards@example.com',
    phone: '+1-234-567-8900',
    alternatePhone: '+1-234-567-8901',
    yearOfBirth: '1995',
    gender: 'Male',
    address: '123 Main Street, New York',
    pincode: '10001',
    state: 'New York',
    country: 'USA',
    school: 'Stanford University',
    degree: 'Bachelor',
    course: 'Computer Science',
    yearOfCompletion: '2018',
    grade: 'A',
    skills: 'React, Node.js, JavaScript, TypeScript, MongoDB, PostgreSQL',
    projects: 'E-commerce Platform, Real-time Chat Application, Analytics Dashboard',
    workExperience: [
      {
        id: '1',
        domain: 'Software Development',
        subDomain: 'Frontend',
        experience: '5 years',
      },
      {
        id: '2',
        domain: 'Software Development',
        subDomain: 'Full Stack',
        experience: '2 years',
      },
    ],
    linkedinUrl: 'linkedin.com/in/daverichards',
    resume: 'DaveRichards_Resume.pdf',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    phone: '+1-987-654-3210',
    alternatePhone: '',
    yearOfBirth: '1998',
    gender: 'Female',
    address: '456 Oak Avenue, California',
    pincode: '90001',
    state: 'California',
    country: 'USA',
    school: 'MIT',
    degree: 'Master',
    course: 'Data Science',
    yearOfCompletion: '2020',
    grade: 'A+',
    skills: 'Python, Machine Learning, TensorFlow, Pandas, SQL, Spark',
    projects: 'Predictive Analytics Model, AI Chatbot, Recommendation Engine',
    workExperience: [
      {
        id: '1',
        domain: 'Data Science',
        subDomain: 'ML Engineering',
        experience: '3 years',
      },
    ],
    linkedinUrl: 'linkedin.com/in/janesmith',
    resume: 'JaneSmith_Resume.pdf',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];